name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # 프로젝트 디렉토리 생성 (없다면)
          mkdir -p /app/startup-trpg/frontend
          cd /app/startup-trpg/frontend
          
          # Git 저장소가 없다면 clone, 있다면 pull
          if [ ! -d ".git" ]; then
            git clone https://github.com/${{ github.repository }}.git .
          else
            git pull origin main
          fi
          
          # 배포 실행
          chmod +x deploy.sh
          ./deploy.sh