name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Git 설치 (Amazon Linux 2용)
          sudo yum update -y
          sudo yum install -y git curl
          
          # 현재 사용자의 홈 디렉토리 확인
          HOME_DIR=$(echo $HOME)
          echo "홈 디렉토리: $HOME_DIR"
          
          # 홈 디렉토리에 프로젝트 생성
          mkdir -p $HOME_DIR/startup-trpg-frontend
          cd $HOME_DIR/startup-trpg-frontend
          
          # Git 저장소가 없다면 clone, 있다면 pull
          if [ ! -d ".git" ]; then
            git clone https://github.com/StartupTRPG/frontend.git .
          else
            git pull origin main
          fi
          
          # Docker 설치 확인
          if ! command -v docker &> /dev/null; then
            echo "Docker가 설치되지 않았습니다. Docker를 먼저 설치해주세요."
            exit 1
          fi
          
          # Docker Compose 설치 확인
          if ! command -v docker-compose &> /dev/null; then
            echo "Docker Compose가 설치되지 않았습니다. Docker Compose를 먼저 설치해주세요."
            exit 1
          fi
          
          # deploy.sh가 있는지 확인하고 실행
          if [ -f "deploy.sh" ]; then
            chmod +x deploy.sh
            ./deploy.sh
          else
            echo "deploy.sh 파일이 없습니다. 수동으로 배포합니다."
            # 기본 배포 명령어
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
          fi